INFO - 2023-11-02 06:13:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-11-02 06:13:54 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-11-02 06:13:54 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_mahasiswa`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-11-02 06:13:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-11-02 06:15:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-11-02 06:15:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-11-02 06:16:08 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\Xampp\htdocs\latihanci4_luthfy\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 D:\Xampp\htdocs\latihanci4_luthfy\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-11-02 06:16:08 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_mahasiswa`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs\\latihanci4_luthfy\\public\\index.php')
ERROR - 2023-11-02 06:16:25 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-11-02 06:16:25 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_mahasiswa`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-11-02 06:16:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-11-02 06:16:48 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-11-02 06:16:48 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_mahasiswa`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
INFO - 2023-11-02 06:18:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-11-02 06:18:54 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=18308 in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'D:\\Xampp\\htdocs...', 185)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#7 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#10 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next mysqli_sql_exception: MySQL server has gone away in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-11-02 06:18:54 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=19172 in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'D:\\Xampp\\htdocs...', 185)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#7 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#10 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\Xampp\htdocs\latihanci4_luthfy\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#13 {main}

Next mysqli_sql_exception: MySQL server has gone away in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\Xampp\htdocs\latihanci4_luthfy\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 D:\Xampp\htdocs\latihanci4_luthfy\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-11-02 06:18:54 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_mahasiswa`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-02 06:18:54 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_mahasiswa`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs\\latihanci4_luthfy\\public\\index.php')
ERROR - 2023-11-02 06:19:25 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=2896 in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'D:\\Xampp\\htdocs...', 185)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#7 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#10 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next mysqli_sql_exception: MySQL server has gone away in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-11-02 06:19:25 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=19172 in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'D:\\Xampp\\htdocs...', 185)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#7 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#10 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\Xampp\htdocs\latihanci4_luthfy\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#13 {main}

Next mysqli_sql_exception: MySQL server has gone away in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\Xampp\htdocs\latihanci4_luthfy\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 D:\Xampp\htdocs\latihanci4_luthfy\system\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs...')
#11 {main}
ERROR - 2023-11-02 06:19:25 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=2896 in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'D:\\Xampp\\htdocs...', 185)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#7 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#10 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next mysqli_sql_exception: MySQL server has gone away in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'db_latihan', 3306, '', 0)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#9 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in D:\Xampp\htdocs\latihanci4_luthfy\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Xampp\htdocs\latihanci4_luthfy\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\Xampp\htdocs\latihanci4_luthfy\app\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
#7 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
#8 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-11-02 06:19:25 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_mahasiswa`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-02 06:19:25 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_mahasiswa`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-02 06:19:25 --> Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_mahasiswa`', [], false)
 3 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Mahasiswa.php(13): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Mahasiswa->index()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Mahasiswa))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\Xampp\\htdocs\\latihanci4_luthfy\\public\\index.php')
CRITICAL - 2023-11-02 07:50:12 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:50:12 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(14.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(14.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(14680064)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 07:51:34 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:51:34 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(4.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(4.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(4194304)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 07:51:34 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:51:35 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(4.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(4.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(4194304)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 07:53:30 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:53:30 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(16.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(16.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(16777216)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 07:53:33 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:53:33 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(4.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(4.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(4194304)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 07:53:34 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:53:34 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(4.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(4.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(4194304)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 07:53:38 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:53:38 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(4.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(4.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(4194304)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 07:54:57 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:54:57 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(16.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(16.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(16777216)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 07:58:51 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:58:51 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(14.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(14.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(14680064)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 07:58:51 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:58:51 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(10.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(10.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(10485760)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 07:58:51 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:58:51 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(8.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(8.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(8388608)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 07:58:52 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:58:52 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(6.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(6.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(6291456)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 07:58:52 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:58:52 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(6.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(6.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(6291456)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 07:58:56 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 07:58:56 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(4.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(4.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(4194304)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 08:14:21 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 08:14:21 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(14.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(14.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(14680064)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 08:14:21 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 08:14:22 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(8.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(8.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(8388608)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 08:14:22 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 08:14:22 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(8.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(8.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(8388608)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 08:14:22 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 08:14:22 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(6.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(6.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(6291456)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 08:14:22 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 08:14:22 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(6.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(6.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(6291456)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 08:14:35 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 08:14:35 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(4.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(4.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(4194304)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 08:14:58 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 08:14:58 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(4.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(4.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(4194304)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 08:17:38 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 08:17:38 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(4.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(4.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(4194304)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 08:17:44 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 08:17:44 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(4.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(4.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(4194304)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-11-02 08:19:18 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-11-02 08:19:19 --> Uncaught Error: Class "Locale" not found in D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php:136
Stack trace:
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\Helpers\number_helper.php(55): format_number(4.0, 2, NULL, Array)
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(145): number_to_size(4.0, 2)
#2 D:\Xampp\htdocs\latihanci4_luthfy\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(4194304)
#3 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(241): include('D:\\Xampp\\htdocs...')
#4 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'D:\\Xampp\\htdocs...')
#6 D:\Xampp\htdocs\latihanci4_luthfy\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 D:\Xampp\htdocs\latihanci4_luthfy\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 D:\Xampp\htdocs\latihanci4_luthfy\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
